name: Test Fantasy Funball Streamlit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FANTASY_FUNBALL_URL: "http://localhost:8080/fantasy_funball/"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest poetry
          if [ -f poetry.lock ]; then
            poetry install;
          fi

      - name: Unit tests
        run: poetry run pytest
